# Nome da aplicação
spring.application.name=literalura

# URL de conexão: 'localhost' funciona pois o Java e o Postgres estão no mesmo ambiente (WSL2)
# 'literalura_db' é o nome do banco que você criou com o comando CREATE DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura_db
spring.datasource.username=postgres
spring.datasource.password=root@3581

# Driver oficial do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Estratégia do Hibernate: 'update' cria as tabelas no banco automaticamente baseado no seu código Java
spring.jpa.hibernate.ddl-auto=update

# Dialect do Hibernate para PostgreSQL (ajuda o ORM a gerar SQL otimizado para o Postgres)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações de Log: Mostra as queries SQL no console (útil para aprender e debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true